version: '2.2'
services:
  sqlserver2005:
    image: core/sqlserver2005
    environment:
      - HAB_LICENSE=accept-no-persist
  sqlwebadmin:
    image: $HAB_ORIGIN/sqlwebadmin
    environment:
      - HAB_LICENSE=accept-no-persist
    ports:
      - 8099:8099
    links:
      - sqlserver2005
    depends_on:
      - sqlserver2005
    command: --peer sqlserver2005 --bind database:sqlserver2005.default

networks:
  default:
    external:
      name: nat
